### PR TITLE
Add 2000 break point

### PR DESCRIPTION
**Pull request by krono**
Regenerate color range based on matplotlib plasma
(`['#15b01a']+ list(map(matplotlib.colors.rgb2hex, matplotlib.cm.get_cmap('plasma').reversed()([1/6*x for x in range(7)])))`)

### CODE REVIEW

**Comment by krono** [comment]
Thanks to 05-15 range in Elbe-Elster…

**Comment by krono** [comment]
Ping @semohr

**Comment by semohr** [comment]
Sorry was a bit occupied the last few days. Was thinking about changing the colormap for quite some time now (I was divided between reversed virdis and plasma), looks good :+1: . Just a heads up, I will remove the 1000 and 2000 incidence limits again once the situation looks a bit different.

**Comment by krono** [comment]
Thanks, that makes a lot of sense.

**Pull request merged**
